### ISSUE TITLE
Doesn't boot. Kernel panics.

### ISSUE THREAD

**Issue by crazo7924** [crazo7924/android_kernel_realme_RMX3241#1]
[last_kmsg.log](https://github.com/crazo7924/android_kernel_realme_RMX3241/files/8244646/last_kmsg.log)

**Comment by crazo7924** [comment]
New logs

[testboot.log](https://github.com/crazo7924/android_kernel_realme_RMX3241/files/8600673/testboot.log)

**Comment by aScordino** [comment]
Hey,

As I suggested on your PMs, you should try to remove the `oppo_phoenix` driver from your kernel, since it was mainly used for **debugging** by _Oplus_ and causes random logspam/kernel panics.

I've already sent you the commit to solve this, but I'm resending it here just because "why not":
 - https://github.com/MinatiScape/RMX2020/commit/40200bdf84ce584ac93d73a172504dd5c1b77af8
 - https://github.com/sarthakroy2002/kernel_realme_RMX2020/commit/b879d6dd4ef7d9f67ccb418b0239febf5df14c7e
Both of these are god, just follow what they deleted and be careful with rebrands from `oppo` to `oplus` etc., since **RMX2020** is a pre-oplus device (as far as I know).

**Comment by aScordino** [comment]
Also, just noticed this is **Realme 8** kernel, not **Realme 8 5G**, which uses a totally different SoC. Consider this a waste of time.

**Comment by crazo7924** [comment]
> Also, just noticed this is **Realme 8** kernel, not **Realme 8 5G**, which uses a totally different SoC (one is **Helio G95**, while the other one is **Dimensity 700**).

I'm trying to port sources from Xiaomi camellia(dimensity 700), realme 8i and 8.

> Consider this a waste of time.

Yes, it is...
